DROP TABLE IF EXISTS pizza;
DROP TABLE IF EXISTS pizza_stonks;

CREATE TABLE pizza (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  url TEXT UNIQUE NOT NULL
);

CREATE TABLE pizza_stonks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  price TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES pizza (id)
);
